---
##############################
# xStaffx Created by xFlare, and pushed by TheDeibo :D
# Your using version 2.0.0
# The Original Code is Of xFlare's xRulesx
##############################


#Add staff below, You may leave some blank.
#You may also use some of the staff slots as a title slot
staff1: "Example"
staff2: "Example"
staff3: "Example"
staff4: "Example"
staff5: "Example"
staff6: "Example"
staff7: "Example"
staff8: "Example"
#Please do not add more Staff slots!
#It may corrupt the config file!
...
